[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "downloads-organizer"
version = "0.1.0"
description = "Organize downloaded files into categorized folders."
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
    { name = "Abbas Endari", email = "a.endari@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[project.scripts]
downloads-organizer = "downloads_organizer.main:main"
[project.urls]
Homepage = "https://github.com/a-endari/downloads-organizer"
